/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.6/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
    id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.0.3"
}

rootProject.name = "kotlin-gradle-cdk-lambda"
include("infrastructure", "lambda", "torch-elt")

gitHooks {
    preCommit {
        from(file("./custom-hooks/pre-commit"))
    }
    createHooks(true)
}
